# Generated by Django 5.0.3 on 2024-03-10 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[('processing', 'Processing'), ('done', 'Done')], default='processing')),
                ('resolution', models.TextField(null=True)),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dialog')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField()),
                ('text', models.TextField()),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dialog')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('correction_text', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.message')),
            ],
        ),
        migrations.CreateModel(
            name='UserDialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('unread_messages', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dialog')),
            ],
        ),
    ]
